# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0002_auto_20170811_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='trailer_youtube_id',
            field=models.CharField(default='null', max_length=15),
            preserve_default=False,
        ),
    ]
