# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0003_movies_trailer_youtube_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='trailer_youtube_id',
        ),
    ]
