# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trailer', '0004_remove_movies_trailer_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='trailer_youtube_id',
            field=models.CharField(default='NIWwJbo-9_8', max_length=20),
            preserve_default=False,
        ),
    ]
